#!/usr/bin/env bash
# usage: routestojson.sh
# Converts all pdfs in /assets/route_pdfs to their corresponding json files.
pdfdir=../assets/route_pdfs
datadir=../data

for f in "$pdfdir"/*; do
  name="$(basename "$f")"
  ./pdftojson "$f" >"$datadir/${name%.*}".json
done
